import { Inter } from "next/font/google";

import "./global.scss";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1"
      />

      <body className={cn(inter.className, 'relative flex min-h-screen flex-col')}>{children}</body>
    </html>
  );
}
